name: Node.js deploy

on:
  push:
    branches: [ "master" ]
jobs:
  gh-pages-deploy:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: yarn && npm run build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          VITE_SMB_API: ${{ secrets.VITE_SMB_API }}
          VITE_RPC_1: ${{ secrets.VITE_RPC_1 }}
          VITE_RPC_2: ${{ secrets.VITE_RPC_2 }}
          VITE_RPC_3: ${{ secrets.VITE_RPC_3 }}


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/spa
